trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 01azdo-agent-container-images/alpine/**
    exclude:
      - '**/*.md'

pool:
  name: pool-eph-agent-dev
  demands: agent_type -equals ubuntu24

variables:
  - group: acr-build-vars   # ACR_NAME, ACR_MI_CLIENT_ID

jobs:
  - job: BuildAlpine
    displayName: Build and push alpine
    steps:
      - template: templates/steps/acr-build-push.yml
        parameters:
          imageName: alpine
          acrName: $(ACR_NAME)
          acrMiClientId: $(ACR_MI_CLIENT_ID)
